services:
  budgetPlannerServer:
    image: budgetplannerserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    environment:
      - Otlp__Endpoint=http://otel-lgtm:4317
      - OTEL_METRIC_EXPORT_INTERVAL=5000 # so we don't have to wait 60s for metrics